### ISSUE TITLE
DrugGCN: pop from an empty deque

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DrugGCN#3]
```
singularity exec --nv --bind /software/improve/data_dir//DrugGCN:/candle_data_dir /software/improve/images//DrugGCN.sif train.sh 2 /candle_data_dir --learning_rate 4.789664088323155e-05 --batch_size 512 --epochs 5 --experiment_id EXP005 --run_id run_01_001_0003

....

Traceback (most recent call last):
  File "/usr/local/DrugGCN/druggcn_baseline_tensorflow.py", line 234, in <module>
    main()
  File "/usr/local/DrugGCN/druggcn_baseline_tensorflow.py", line 230, in main
    run(gParameters)
  File "/usr/local/DrugGCN/druggcn_baseline_tensorflow.py", line 166, in run
    loss, t_step = model.fit(train_data_V, train_labels_V, val_data, val_labels)
  File "/usr/local/DrugGCN/lib/models.py", line 129, in fit
    idx = [indices.popleft() for i in range(self.batch_size)]
  File "/usr/local/DrugGCN/lib/models.py", line 129, in <listcomp>
    idx = [indices.popleft() for i in range(self.batch_size)]
IndexError: pop from an empty deque
```

**Comment by jonesse3** [comment]
@wilke Updated both `improve` and `develop` branches. Addressed this error by adding try/except block that will exit program if the batch size is greater than the train dataset size in `models.py`. Additionally added code to identify and print out the maximum batch size that can be used in `druggcn_baseline_tensorflow.py`.
